import { Button, VerticalBox, HorizontalBox, Palette } from "std-widgets.slint";

export component MainWindow inherits Window {
    always-on-top: true; // Dev feature
    title: "FlockVPN";
    width: 400px;
    height: 600px;

    VerticalLayout {
        alignment: start;

        Rectangle {
            VerticalLayout {
                HorizontalBox {
                    alignment: space-between;

                    HorizontalLayout {
                        spacing: 0.5rem;

                        VerticalLayout {
                            alignment: center;
                            padding-bottom: 2.5px;
                            Rectangle {
                                width: 10px;
                                height: 10px;
                                border-radius: 10px;
                                background: oklch(71.1%, 0.029, 164.0);
                            }
                        }

                        Text {
                            text: "Online";
                            font-size: 1rem;
                            font-weight: FontWeight.bold;
                            vertical-alignment: center;
                        }
                    }

                    Button {
                        primary: true;
                        colorize-icon: true;
                        icon: @image-url("../assets/icons-ui/settings.svg");
                    }
                }

                Rectangle {
                    height: 0.5px;
                    background: Palette.border;
                }
            }
        }
    }
}
